app:
    name: Quick Start
    description: Start with Spring boot

connection:
    username: test
    remoteAddress: 127.0.0.1
---
spring:
    profiles: development
server:
    address: 127.0.0.1
---
spring:
    profiles: production
server:
    address: 192.168.1.120